### PR TITLE
Reduce noise in gym

### PR DESCRIPTION
**Pull request by teytaud**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

We want less noise.

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](https://facebookresearch.github.io/nevergrad/contributing.html) document and completed the CLA (see [**CLA**](https://facebookresearch.github.io/nevergrad/contributing.html#contributor-license-agreement-cla)).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by teytaud** [comment]
For some reason impossible to add @mathuvu as a reviewer...

**Comment by jrapin** [comment]
Can you explain what this does as a comment, because I don't get it at all, it seems obscure to change the noise little by little

**Comment by jrapin** [comment]
> For some reason impossible to add @mathuvu as a reviewer...

Added to the nevergrad team

**Comment by teytaud** [comment]
> > For some reason impossible to add @mathuvu as a reviewer...
> 
> Added to the nevergrad team

Thanks @jrapin

**Comment by teytaud** [comment]
> Can you explain what this does and why as a comment (so that we can understand when rereading later), because I don't get it at all, it seems obscure to change the noise little by little

Comment added. The goal is to reduce the noise, while not spending more than 20% of the budget of the experiment.

**Review by jrapin — APPROVED** [review]
I feel this is a bit of an unexpected behavior, but that's for you to decide so merge if confortable

**Pull request merged**
