### PR TITLE
62-custom-file-types

### PR DESCRIPTION
**Pull request by Dominik1123**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

Using custom file types for token instrumentation raised an exception as detailed in #62 . Using custom file types (extensions) was therefore not possible.

## How Has This Been Tested (if it applies)

```
nosetests nevergrad
nosetests nevergrad.instrumentation.test_instantiate
```

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by jrapin** [comment]
Looks good to me, thank you!
2 remarks:
- I may add back the `extensions` parameters of `FolderFunction` eventually. Its goal was to help focus on one type of file and avoid parsing a full project. May have been over-optimization though, so I'll see if the need arises or not.
- any specific reason for using a `dict` with only a "comment" key: `".c": dict(comment="//")`? This seems unnecessary to me. I may remove it eventually if you do not see any future use.

**Comment by Dominik1123** [comment]
No, I didn't have a strong reason for using another `dict`, but having a variable `FILE_TYPES` it seemed clearer to mark the comment chars explicitly as such by adding the "comment" key dict. But could be renamed to `COMMENT_CHARS` for example and then leave out the innermost `dict`.

Regarding the extensions parameter for filtering project files, maybe it would be more convenient to let the user specify a regex or wildcard pattern and only consider matching files? That way filtering by extensions would be included as a special case (e.g. `"*.c"`) while allowing for more complex filters as well.

**Comment by jrapin** [comment]
`COMMENT_CHARS` seems good to me. Either you want to change this yourself, or I merge now and I will do it eventually (but I am in no hurry, it does not change the interface anyway).

regex seems a good idea indeed! Let's just remove the `extensions` parameter for now as you did, and when we need filtering we'll add regex ;)

**Comment by Dominik1123** [comment]
Done :-)

**Comment by jrapin** [comment]
Thanks a lot!

**Pull request merged**
