### PR TITLE
Update JNGO

### PR DESCRIPTION
**Pull request by ljialin**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [ ] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by teytaud** [comment]
you just have te remove ./nevergrad/optimization/recorded_recommendations.csv
then pytest nevergrad --cov=nevergrad
==> this is because results of optimizers are recorded as a test of consistency, when an optimizer is added or modified we must remove the records so that they are re-recorded.

**Comment by jrapin** [comment]
The file was completely remove this time, which is not good either :D you would need to recreate it by running pytest. This is done through `pytest nevergrad/optimization/test_optimizerlib.py`, first once to recreate the file (it will show plenty of errors, saying new value were recorded), then another time to make sure everything works correctly (hopefully no more errors).
I'll try to do that for you now

**Comment by jrapin** [comment]
@ljialin please merge this PR in your branch: https://github.com/ljialin/nevergrad/pull/1, that should fix the issue with recorded recommendations.
Sorry for if this is a bit complicated, this is the only possible way we can check we have perfect reproducibility on algorithms, and that a random PR does not modify the algorithms when they should not (here it's expected to change so it's alright). If you have this problem again we can go through the steps together, it's not difficult but it probably needs a bit of practice ;)

**Comment by jrapin** [comment]
Also, don't hesitate to reach out to me for help if you have any problem with the continuous integration checks (or any other issue) ;)

**Comment by ljialin** [comment]
> There were some misaligned indents in `test_optimizerlib.py`, causing the errors. I've removed those manually. More generally the indents seem a bit weird, is it fro m your editor? Anyway I'll sort that out later when this is merged. I've also changed the destination branch to master (and solved the conflicts, maybe crosscheck that I didn't do anything stupid ;) ), so it's good to go for me, @teytaud anything to add? If not, you can "Squash & Merge"

Ah! I did not even realise it was due to indents. Could be included by my editor. I will configure it. Thank you!

**Comment by jrapin** [comment]
@ljialin it seems you closed the PR, is it normal? You can leave it that way, and if you are OK I'll go ahead and merge it as it is (@teytaud is OK), I can clean up the indentation easily (I'll use [black](https://github.com/psf/black) so it's only one commandline, I just didnt want to do it inside your PR because it would have made many other unrelated changes ;)).
When your PR is merged, I'll also relase a new stable version of nevergrad, since I'm going to make many changes soon that may create some bug, that we'll try to solve asap

**Comment by teytaud** [comment]
Cool code, merged in another branch.

**Pull request closed without merging**
