### PR TITLE
sequential or fully parallel ML.

### PR DESCRIPTION
**Pull request by teytaud**
This benchmark has not been much used for the moment, let us make it shorter and clearer.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](https://facebookresearch.github.io/nevergrad/contributing.html) document and completed the CLA (see [**CLA**](https://facebookresearch.github.io/nevergrad/contributing.html#contributor-license-agreement-cla)).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Review by jrapin — COMMENTED** [review]
Why do you remove all middle ground between one shot and sequential?
I feel this is not representative at all of mltuning cases

**Comment by teytaud** [comment]
> Why do you remove all middle ground between one shot and sequential?
> I feel this is not representative at all of mltuning cases

Just because I feel these two extreme cases are the priority these days.

**Comment by jrapin** [comment]
> > Why do you remove all middle ground between one shot and sequential?
> > I feel this is not representative at all of mltuning cases
> 
> Just because I feel these two extreme cases are the priority these days.

why so? typical workflows in my understanding would have something like 4 passes

**Comment by teytaud** [comment]
> > > Why do you remove all middle ground between one shot and sequential?
> > > I feel this is not representative at all of mltuning cases
> > 
> > 
> > Just because I feel these two extreme cases are the priority these days.
> 
> why so? typical workflows in my understanding would have something like 4 passes

Ok then in a perfect world I'd like to have three cases so that we can see what happens but ok it's slow enough, I appreciate the recent speed, so let's have [1, budget//4] and [budget]; after all the subplots will distinguishes the different cases in the dashboard.

**Pull request merged**
