### PR TITLE
update plotting.py for taking into account 007

### PR DESCRIPTION
**Pull request by teytaud**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](https://facebookresearch.github.io/nevergrad/contributing.html) document and completed the CLA (see [**CLA**](https://facebookresearch.github.io/nevergrad/contributing.html#contributor-license-agreement-cla)).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Review by jrapin — CHANGES_REQUESTED** [review]
This is a fix for a plot, but should not be in the repo. If there are more cases where this need arises with other names, I'll come up with something else.

**Review by jrapin — COMMENTED** [review]
I guess I'll need to do something more generic than this, I dont really like adding special cases for some arguments like this

**Comment by jrapin** [comment]
@teytaud #860 will provide a way to merge the optimizer name with any other descriptor in the commandline, it should replace this hack and allow much more.

**Comment by teytaud** [comment]
Deprecated.

**Pull request closed without merging**
