### PR TITLE
Modification of torch version to avoid seg fault

### PR DESCRIPTION
**Pull request by fteytaud**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] The documentation is up-to-date with the changes I made.
- [ ] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [ ] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by jrapin** [comment]
Still `ImportError: dlopen: cannot load any more object with static TLS`?
I hoped the previous changed at fixed it (it fixed it for us at least).
@fteytaud before we are allowed to merge, you will need to sign the CLA (which basically means you agree that we can share your code in this repository under the provided MIT license)

**Comment by jrapin** [comment]
Seems good. Hopefully we can move to more recent versions when this is fixed in pytorch (on its way as far as i understand)

**Comment by jrapin** [comment]
Hi @fteytaud this version of pytorch is actually causing issues for us internally, have you tried with version 1.2.0 instead?

**Comment by fteytaud** [comment]
Hi, I get a `Segmentation fault (core dumped)` with torch 1.2 (or 1.1). Am I the only one ?

**Comment by jrapin** [comment]
1.2.0 works fine for us so far, 1.3.1 breaks the CI as far as we know
https://circleci.com/gh/facebookresearch/nevergrad/1712?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link (a test we ran just now to check it again)
and 1.0.1 is not recent enough for some integration we have internally though.
I dont understand why 1.2 works for us and not for you though :s

**Comment by fteytaud** [comment]
I don't know, I have an ubuntu 18.04.
Do not hesitate to change to 1.2 if it's necessary ; I will find a solution for me :)

**Pull request merged**
