### PR TITLE
Adding SPSA

### PR DESCRIPTION
**Pull request by se4u**
## Motivation and Context

Adding SPSA algorithm.

https://github.com/facebookresearch/nevergrad/issues/4

## How Has This Been Tested

Currently the test `nosetests nevergrad/optimization/test_optimizerlib.py` fails. Hence the WIP tag.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Changed `nevergrad/benchmark/experiments.py` and `nevergrad/optimization/optimizerlib.py`

## Checklist

- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jrapin** [comment]
I figured out the issue. Actually when you seed the random state, then it works. You still had an error because when you tried, you had already created a history for your algorithm from your previous attempts, which differed from the output you got with the seed. After deleting the file and rerunning, it worked.

But since we don't want to seed the random state, it does not solve the problem. I expected the RandomState to get its default seed from the default random generator, but it was a wrong assumption: f you create it without seed, we cannot seed from outside. I have modified the guidelines to state that one should initialize it this way then:
```python
self._rng = np.ranndom.RandomState(np.random.randint(2**32))
 ```
After this, it works!

Concerning the other error, I have updated the test to avoid using multiple workers on non-parallel optimizers. You're optimizer seems to be a bit slow to converge though. If it's normal (that's often what happens for optimizers dealing with noise), you can add it to the list of "SLOW" optimizers, in the test file:
https://github.com/facebookresearch/nevergrad/blob/0c29a99da53c484731dfb512df13744b39794656/nevergrad/optimization/test_optimizerlib.py#L47

**Comment by se4u** [comment]
The tests now pass and I added a benchmark `spsa_benchmark` which gives results like the following:


Fig 1a. rotation_False | Fig 1b. rotation_true
:-------------------------:|:-------------------------:
fight_rotationfalse |  fight_rotationtrue

Fig 2a. Sphere | Fig 2b. Sphere4 | Fig 2c. Cigar
:--------------:|:-----------:|:-----------:
fight_namesphere |  fight_namesphere4 |  fight_namecigar

There are still [two comments about `todo` items](https://github.com/facebookresearch/nevergrad/pull/16/commits/c8ea286592b23aabb2a7b4cce93613cac4299ba5#diff-392c981c3de5c2d86ed5864cf03abbbaR469)  related to estimating the noise standard deviation and the gradient magnitude of the function in the beginning of the optimization, but they don't really change the overall picture shown in the benchmarks.

**Comment by se4u** [comment]
Here are the plots 

1. cigar rotationfalse
2. cigar rotationtrue
3. sphere rotationfalse
4. sphere rotationtrue
5. sphere4 rotationfalse
6. sphere4 rotationtrue


xpresults_namecigar rotationfalse
xpresults_namecigar rotationtrue
xpresults_namesphere rotationfalse
xpresults_namesphere rotationtrue
xpresults_namesphere4 rotationfalse
xpresults_namesphere4 rotationtrue

**Comment by se4u** [comment]
@teytaud Totally agree to your points.

@jrapin I think this PR is ready to merge now. I left the TODOs in, with the two hardcoded parameters.

**Comment by jrapin** [comment]
Let's go then ;) Thank you!

**Pull request merged**
