### PR TITLE
Add the eps criterion for selecting subsets

### PR DESCRIPTION
**Pull request by teytaud**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

favorite tool by Markus so worth being tested

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](https://facebookresearch.github.io/nevergrad/contributing.html) document and completed the CLA (see [**CLA**](https://facebookresearch.github.io/nevergrad/contributing.html#contributor-license-agreement-cla)).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by jrapin** [comment]
can you describe what is eps?

**Comment by teytaud** [comment]
EPS is the epsilon indicator defined here: https://hal.archives-ouvertes.fr/hal-01159961v2/document

EPS is the classical notion for this.

**Comment by teytaud** [comment]
> EPS is the epsilon indicator defined here: https://hal.archives-ouvertes.fr/hal-01159961v2/document
> 
> EPS is the classical notion for this.

(added as a comment)

**Comment by jrapin** [comment]
> > EPS is the epsilon indicator defined here: https://hal.archives-ouvertes.fr/hal-01159961v2/document
> > EPS is the classical notion for this.
> 
> (added as a comment)

This should be in the docstring, not the comment, because it can be helpful for users. The others selection methods should also be documented btw.
Also the name should be `EPS` then, not `eps`, to match what you

**Review by jrapin — APPROVED** [review]

**Pull request merged**
