### PR TITLE
Allow repetitions for Choice parameters

### PR DESCRIPTION
**Pull request by jrapin**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

This seems a common scheme that could be handled more efficiently to scale better.

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](https://facebookresearch.github.io/nevergrad/contributing.html) document and completed the CLA (see [**CLA**](https://facebookresearch.github.io/nevergrad/contributing.html#contributor-license-agreement-cla)).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by jrapin** [comment]
30 times faster

```python
In [16]: %cpaste -q
import time
import nevergrad as ng

t0 = time.time()
param = ng.p.Tuple(*[ng.p.Choice(range(64)) for _ in range(100000)])
param.mutate()
v = param.value
print("v1", time.time() - t0)

t0 = time.time()
param = ng.p.Choice(range(64), repetitions=100000)
param.mutate()
v = param.value
print("v2", time.time() - t0)
--
v1 104.45756006240845
v2 3.4510011672973633
```

**Comment by danthe3rd** [comment]
> 30 times faster

On how many CPUs? Can you also measure using a single CPU?

**Comment by jrapin** [comment]
> > 30x faster
> 
> On how many CPUs? Can you also measure using a single CPU?

This is on my macbook pro, there is no parallelization apart from the one that may be in numpy, i think it's 1 CPU then

**Comment by teytaud** [comment]
Waow that one is really GREAT :-)

**Pull request merged**
