### PR TITLE
Photonics long problems

### PR DESCRIPTION
**Pull request by teytaud**
Not for the standard dashboard --- for finding big cool solutions to beautiful challenging problems :-)

@anmoreau

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](https://facebookresearch.github.io/nevergrad/contributing.html) document and completed the CLA (see [**CLA**](https://facebookresearch.github.io/nevergrad/contributing.html#contributor-license-agreement-cla)).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by teytaud** [comment]
The "autosuggest" stuff would be for here (as discussed here: https://github.com/facebookresearch/nevergrad/pull/762).

**Review by jrapin — COMMENTED** [review]
I think this will never reach the end :s for morpho it's been very hard to reach 1e6 on the cluster :s

**Comment by teytaud** [comment]
how parallel were you and how long was the experiments (even very roughly ?).

**Comment by teytaud** [comment]
(the plan is to be in "no limit" mode, with the leaderboard and the set/get there)

**Comment by jrapin** [comment]
> how parallel were you and how long was the experiments (even very roughly ?).

the benchmark mock parallelism, so in the end it's always sequential. and it would take about 7 days for 10e4

**Pull request closed without merging**
